version: '3'
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    ports:
      - ${PORT}:${PORT}
    environment:
      - PORT=${PORT}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - API_KEY_EMAIL=${API_KEY_EMAIL}
      - API_KEY_PASSWORD=${API_KEY_PASSWORD}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_ORGANIZATION=${OPENAI_ORGANIZATION}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - BRAVE_SEARCH_API_KEY=${BRAVE_SEARCH_API_KEY}
      - LANGCHAIN_TRACING_V2=${LANGCHAIN_TRACING_V2}
      - LANGCHAIN_ENDPOINT=${LANGCHAIN_ENDPOINT}
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}
      - LANGCHAIN_PROJECT=${LANGCHAIN_PROJECT}
    volumes:
      - temp_img:/api/modules/wp/temp
    networks:
      - apinetwork

  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    restart: always
    ports:
      - ${STREAMLIT_PORT}:8501
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - AGC_API_URL=http://api:${PORT}
      - AGC_API_USERNAME=${API_KEY_EMAIL}
      - AGC_API_PASSWORD=${API_KEY_PASSWORD}
    networks:
      - apinetwork

volumes:
  temp_img:
    driver: local

networks:
  apinetwork:
    driver: bridge
